language: ruby
rvm:
  - "1.9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database tag_cloud_test;' -U postgres
  - bundle exec rake db:migrate db:test:prepare
script: bundle exec rspec spec

